repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/crate-ci/typos
    rev: v1.35.3
    hooks:
      - id: typos
        exclude: '^.*\.(ogg|mp3|csv)'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace
        exclude: '^.*\.(ogg|mp3)'
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-check
