repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace
        exclude: '^.*\.(tsv|json|svg)'
      - id: end-of-file-fixer
        exclude: ^tests/.*/fixtures/.*
